volumes :
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ${DATA_DIR}/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ${DATA_DIR}/mariadb
      o: bind
      type: none
services:
  wordpress:
    container_name: incepfion-wordpress
    build: ./wordpress/
    networks:
      - incepfion
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    expose:
      - "9000"
    env_file:
      - .env
    restart: unless-stopped
  mariadb:
    container_name: incepfion-mariadb
    build: ./mariadb/
    networks:
      - incepfion
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    restart: unless-stopped
  nginx:
    container_name: incepfion-nginx
    build: ./nginx/
    networks:
      - incepfion
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    restart: unless-stopped
networks:
  incepfion:
    name: incepfion
    driver: bridge
