volumes :
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/babonnet/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/babonnet/data/mariadb
      o: bind
      type: none
services:
  wordpress:
    container_name: wordpress
    build: ./wordpress/
    networks:
      - incepfion
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    expose:
      - "9000"
    env_file:
      - .env
  mariadb:
    container_name: mariadb
    build: ./mariadb/
    networks:
      - incepfion
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - .env
  nginx:
    container_name: nginx
    build: ./nginx/
    networks:
      - incepfion
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    env_file:
      - .env
networks:
  incepfion:
    name: incepfion
    driver: bridge
